-- Create messages table
create table public.messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  phone text,
  message text not null,
  is_read boolean default false
);

-- Enable RLS
alter table public.messages enable row level security;

-- Create policy to allow anonymous inserts (anyone can send a message)
create policy "Enable insert for everyone" on public.messages for insert
with check (true);

-- Create policy to allow read access only to authenticated users (admin)
create policy "Enable read access for authenticated users only" on public.messages for select
using (auth.role() = 'authenticated');
