-- Crear tabla de Posts para el Blog
create table posts (
  id bigint generated by default as identity primary key,
  title text not null,
  date text not null,
  image text not null,
  author text not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insertar datos de ejemplo (los mismos que teníamos en el código)
insert into posts (title, date, image, author, content) values
(
  'El futuro de la IA en la educación',
  '1 Mar 2025',
  'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
  'Ana G.',
  'La inteligencia artificial está transformando rápidamente la forma en que enseñamos y aprendemos. En Bolivia, tenemos la oportunidad única de adoptar estas tecnologías para cerrar brechas educativas históricas.

## Personalización del Aprendizaje
Uno de los mayores beneficios de la IA es su capacidad para adaptar el contenido al ritmo de cada estudiante. Herramientas como tutores virtuales pueden ofrecer explicaciones adicionales cuando un alumno se atasca, o proponer desafíos mayores cuando detectan facilidad en un tema.

## Automatización Administrativa
Para los profesores, la IA puede ser un asistente incansable, ayudando a calificar exámenes de opción múltiple, organizar horarios y detectar patrones de asistencia, liberando tiempo valioso para la mentoría directa.

## El Desafío Ético
Sin embargo, no todo es tecnología. Debemos enseñar a los estudiantes sobre el uso ético de estas herramientas, la privacidad de los datos y el sesgo algorítmico. En CienciaLink, integramos estos debates en todos nuestros cursos de programación.'
),
(
  'Resumen de la Feria de Ciencias 2024',
  '25 Feb 2025',
  'https://images.unsplash.com/photo-1564325724739-bae0bd08762c?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
  'Carlos M.',
  'La feria de este año fue un éxito rotundo con más de 200 proyectos presentados por estudiantes de todo el país. Desde robots recicladores hasta sistemas de riego automatizado, la creatividad boliviana brilló con luz propia.

## Ganadores Destacados
El primer lugar fue para el equipo "EcoBots" de El Alto, quienes diseñaron un robot capaz de identificar y separar residuos plásticos utilizando visión por computadora básica.

## Próximos Pasos
Los ganadores representarán a Bolivia en la competencia regional en Chile el próximo mes. ¡Les deseamos todo el éxito!'
),
(
  '5 Proyectos con Arduino para principiantes',
  '15 Feb 2025',
  'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
  'Luis P.',
  'Arduino es la mejor plataforma para iniciarse en la electrónica y la programación. Si acabas de comprar tu primer kit, aquí tienes 5 ideas para empezar:

1. **LED Parpadeante**: El "Hola Mundo" de la electrónica. Aprende a controlar pines digitales.
2. **Semáforo Inteligente**: Usa temporizadores para simular un cruce de calles.
3. **Sensor de Temperatura**: Muestra la temperatura ambiente en tu monitor serial.
4. **Alarma de Distancia**: Usa un sensor ultrasónico para detectar intrusos.
5. **Brazo Robótico Simple**: Controla servomotores con potenciómetros.

Todos estos proyectos están cubiertos en nuestro curso de "Robótica con Arduino". ¡Inscríbete hoy!'
);

-- Habilitar acceso público (lectura)
alter table posts enable row level security;

create policy "Permitir lectura pública"
on posts for select
to anon
using (true);
