-- Crear tabla de Cursos
create table courses (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  image text not null,
  price numeric not null,
  instructor text not null,
  duration text not null,
  schedule text not null,
  modality text not null,
  category text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Crear tabla de Inscripciones
create table enrollments (
  id bigint generated by default as identity primary key,
  course_id bigint references courses(id),
  student_name text not null,
  student_email text not null,
  student_phone text not null,
  status text default 'pending', -- pending, confirmed, paid
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insertar Cursos de Ejemplo
insert into courses (title, description, image, price, instructor, duration, schedule, modality, category) values
(
  'Programación en Python desde Cero',
  'Domina el lenguaje más popular del mundo. Desde cero hasta análisis de datos.',
  'https://images.unsplash.com/photo-1526379095098-d400fd0bf935?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
  150,
  'Ing. Carlos Mamani',
  '6 Semanas',
  'Lun-Mie-Vie 19:00 - 21:00',
  'Virtual',
  'programacion'
),
(
  'Robótica con Arduino',
  'Construye y programa tus propios robots. Incluye kit básico de componentes.',
  'https://images.unsplash.com/photo-1555679427-1f6dfcce943b?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
  250,
  'Lic. Ana Torrez',
  '4 Semanas',
  'Sabados 09:00 - 13:00',
  'Presencial',
  'robotica'
),
(
  'Diseño e Impresión 3D',
  'Materializa tus ideas. Aprende modelado 3D y operación de impresoras.',
  'https://images.unsplash.com/photo-1631541909061-71e349d1f203?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
  200,
  'Arq. Luis Perez',
  '4 Semanas',
  'Mar-Jue 18:30 - 20:30',
  'Presencial',
  'diseno'
),
(
  'Desarrollo Web Frontend',
  'Crea sitios web modernos con HTML, CSS y React. Conviértete en desarrollador.',
  'https://images.unsplash.com/photo-1593720213428-28a5b9e94613?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
  180,
  'Ing. Sofia Mendez',
  '8 Semanas',
  'Lun-Mie 19:00 - 21:00',
  'Virtual',
  'programacion'
),
(
  'Inteligencia Artificial Básica',
  'Entiende los fundamentos de la IA y cómo aplicarlos en problemas reales.',
  'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
  220,
  'MSc. Juan Pablo Lima',
  '5 Semanas',
  'Vie 18:00 - 21:00',
  'Virtual',
  'programacion'
),
(
  'Electrónica Digital',
  'Aprende sobre compuertas lógicas, circuitos y microcontroladores.',
  'https://images.unsplash.com/photo-1517077304055-6e89abbf09b0?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
  200,
  'Ing. Roberto Gomez',
  '6 Semanas',
  'Sabados 14:00 - 18:00',
  'Presencial',
  'robotica'
);

-- Habilitar acceso público
alter table courses enable row level security;
alter table enrollments enable row level security;

create policy "Lectura pública de cursos"
on courses for select
to anon
using (true);

create policy "Creación pública de inscripciones"
on enrollments for insert
to anon
with check (true);
