-- Tabla para registrar las compras de kits
create table public.kit_purchases (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  kit_title text not null,
  price text not null,
  customer_name text not null,
  customer_email text not null,
  customer_phone text not null,
  customer_address text
);

-- Habilitar Row Level Security (RLS)
alter table public.kit_purchases enable row level security;

-- Política para permitir que cualquiera (incluso anónimos) pueda insertar pedidos
create policy "Permitir insertar pedidos a todos"
on public.kit_purchases
for insert
to anon
with check (true);

-- Política para permitir ver los pedidos solo a usuarios autenticados (administradores)
-- Asumiendo que usarás autenticación más adelante para un panel de admin
create policy "Permitir ver pedidos solo a autenticados"
on public.kit_purchases
for select
to authenticated
using (true);
