-- Create event_registrations table
create table public.event_registrations (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  event_name text not null,
  name text not null,
  email text not null,
  phone text not null,
  comment text
);

-- Enable RLS
alter table public.event_registrations enable row level security;

-- Create policy to allow anonymous inserts (anyone can register)
create policy "Enable insert for everyone" on public.event_registrations for insert
with check (true);

-- Create policy to allow read access only to authenticated users (admin)
create policy "Enable read access for authenticated users only" on public.event_registrations for select
using (auth.role() = 'authenticated');
